apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: marquez
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: marquez
  minReplicas: {{ default 3 .Values.marquez.replicaCount }}
  maxReplicas: {{ default 10 .Values.marquez.maxReplicaCount }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80