apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: marquez-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: marquez-web
  minReplicas: {{ default 2 .Values.web.replicaCount }}
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80